// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=../../implementations/mock/comment/repository.go
//

// Package mock_comment is a generated GoMock package.
package mock_comment

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	models "github.com/muji40k/ozontestcomms/internal/domain/models"
	collection "github.com/muji40k/ozontestcomms/internal/repository/collection"
	comment "github.com/muji40k/ozontestcomms/internal/repository/interface/comment"
	result "github.com/muji40k/ozontestcomms/misc/result"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateCommentComment mocks base method.
func (m *MockRepository) CreateCommentComment(ctx context.Context, comment models.Comment) (models.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCommentComment", ctx, comment)
	ret0, _ := ret[0].(models.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCommentComment indicates an expected call of CreateCommentComment.
func (mr *MockRepositoryMockRecorder) CreateCommentComment(ctx, comment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCommentComment", reflect.TypeOf((*MockRepository)(nil).CreateCommentComment), ctx, comment)
}

// CreatePostComment mocks base method.
func (m *MockRepository) CreatePostComment(ctx context.Context, comment models.Comment) (models.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePostComment", ctx, comment)
	ret0, _ := ret[0].(models.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePostComment indicates an expected call of CreatePostComment.
func (mr *MockRepositoryMockRecorder) CreatePostComment(ctx, comment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePostComment", reflect.TypeOf((*MockRepository)(nil).CreatePostComment), ctx, comment)
}

// GetCommentsByCommentId mocks base method.
func (m *MockRepository) GetCommentsByCommentId(ctx context.Context, commentId uuid.UUID, order comment.CommentOrder) (collection.Collection[result.Result[models.Comment]], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommentsByCommentId", ctx, commentId, order)
	ret0, _ := ret[0].(collection.Collection[result.Result[models.Comment]])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommentsByCommentId indicates an expected call of GetCommentsByCommentId.
func (mr *MockRepositoryMockRecorder) GetCommentsByCommentId(ctx, commentId, order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommentsByCommentId", reflect.TypeOf((*MockRepository)(nil).GetCommentsByCommentId), ctx, commentId, order)
}

// GetCommentsById mocks base method.
func (m *MockRepository) GetCommentsById(ctx context.Context, ids ...uuid.UUID) (collection.Collection[result.Result[models.Comment]], error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range ids {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCommentsById", varargs...)
	ret0, _ := ret[0].(collection.Collection[result.Result[models.Comment]])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommentsById indicates an expected call of GetCommentsById.
func (mr *MockRepositoryMockRecorder) GetCommentsById(ctx any, ids ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, ids...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommentsById", reflect.TypeOf((*MockRepository)(nil).GetCommentsById), varargs...)
}

// GetCommentsByPostId mocks base method.
func (m *MockRepository) GetCommentsByPostId(ctx context.Context, postId uuid.UUID, order comment.CommentOrder) (collection.Collection[result.Result[models.Comment]], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommentsByPostId", ctx, postId, order)
	ret0, _ := ret[0].(collection.Collection[result.Result[models.Comment]])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommentsByPostId indicates an expected call of GetCommentsByPostId.
func (mr *MockRepositoryMockRecorder) GetCommentsByPostId(ctx, postId, order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommentsByPostId", reflect.TypeOf((*MockRepository)(nil).GetCommentsByPostId), ctx, postId, order)
}
