// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=../../mock/post/service.go
//

// Package mock_post is a generated GoMock package.
package mock_post

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	models "github.com/muji40k/ozontestcomms/internal/domain/models"
	collection "github.com/muji40k/ozontestcomms/internal/repository/collection"
	post "github.com/muji40k/ozontestcomms/internal/service/interface/post"
	result "github.com/muji40k/ozontestcomms/misc/result"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CreatePost mocks base method.
func (m *MockService) CreatePost(ctx context.Context, userId uuid.UUID, form post.PostCreationForm) (models.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePost", ctx, userId, form)
	ret0, _ := ret[0].(models.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePost indicates an expected call of CreatePost.
func (mr *MockServiceMockRecorder) CreatePost(ctx, userId, form any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePost", reflect.TypeOf((*MockService)(nil).CreatePost), ctx, userId, form)
}

// GetPosts mocks base method.
func (m *MockService) GetPosts(ctx context.Context, order post.PostOrder) (collection.Collection[result.Result[models.Post]], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPosts", ctx, order)
	ret0, _ := ret[0].(collection.Collection[result.Result[models.Post]])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPosts indicates an expected call of GetPosts.
func (mr *MockServiceMockRecorder) GetPosts(ctx, order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPosts", reflect.TypeOf((*MockService)(nil).GetPosts), ctx, order)
}

// GetPostsById mocks base method.
func (m *MockService) GetPostsById(ctx context.Context, ids ...uuid.UUID) (collection.Collection[result.Result[models.Post]], error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range ids {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPostsById", varargs...)
	ret0, _ := ret[0].(collection.Collection[result.Result[models.Post]])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostsById indicates an expected call of GetPostsById.
func (mr *MockServiceMockRecorder) GetPostsById(ctx any, ids ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, ids...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostsById", reflect.TypeOf((*MockService)(nil).GetPostsById), varargs...)
}

// UpdatePost mocks base method.
func (m *MockService) UpdatePost(ctx context.Context, userId uuid.UUID, post models.Post) (models.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePost", ctx, userId, post)
	ret0, _ := ret[0].(models.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePost indicates an expected call of UpdatePost.
func (mr *MockServiceMockRecorder) UpdatePost(ctx, userId, post any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePost", reflect.TypeOf((*MockService)(nil).UpdatePost), ctx, userId, post)
}
