// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=../../mock/user/service.go
//

// Package mock_user is a generated GoMock package.
package mock_user

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	models "github.com/muji40k/ozontestcomms/internal/domain/models"
	collection "github.com/muji40k/ozontestcomms/internal/repository/collection"
	result "github.com/muji40k/ozontestcomms/misc/result"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetUsersById mocks base method.
func (m *MockService) GetUsersById(ctx context.Context, ids ...uuid.UUID) (collection.Collection[result.Result[models.User]], error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range ids {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUsersById", varargs...)
	ret0, _ := ret[0].(collection.Collection[result.Result[models.User]])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersById indicates an expected call of GetUsersById.
func (mr *MockServiceMockRecorder) GetUsersById(ctx any, ids ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, ids...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersById", reflect.TypeOf((*MockService)(nil).GetUsersById), varargs...)
}
